
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 16 21:47:23 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 26;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 24;
  public static final int MINUS = 50;
  public static final int RPAREN = 7;
  public static final int GRE = 44;
  public static final int AND = 40;
  public static final int OR = 39;
  public static final int RSQRBRACK = 32;
  public static final int COMMA = 8;
  public static final int CLASS = 28;
  public static final int INC = 37;
  public static final int DIV = 48;
  public static final int PLUS = 11;
  public static final int IF = 18;
  public static final int DOT = 34;
  public static final int FINDANY = 30;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int EQUAL = 12;
  public static final int NEW = 21;
  public static final int error = 1;
  public static final int MUL = 49;
  public static final int GEA = 43;
  public static final int MOD = 47;
  public static final int NUMBER = 16;
  public static final int BREAK = 29;
  public static final int IDENT = 17;
  public static final int VOID = 13;
  public static final int EQU = 46;
  public static final int ARROW = 31;
  public static final int COLON = 35;
  public static final int FOREACH = 25;
  public static final int NEQU = 45;
  public static final int LBRACE = 3;
  public static final int ELSE = 19;
  public static final int READ = 20;
  public static final int CHARCONST = 15;
  public static final int WHILE = 22;
  public static final int LSQRBRACK = 33;
  public static final int LES = 42;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 14;
  public static final int EXTENDS = 23;
  public static final int PROG = 2;
  public static final int DEC = 38;
  public static final int NMSPACE = 27;
  public static final int DOUBLECOLON = 36;
  public static final int PRINT = 9;
  public static final int LEA = 41;
}

